# Generated by Django 4.0.1 on 2022-03-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активации')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус админа')),
                ('first_name', models.CharField(blank=True, default='Анонимный', max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='пользователь', max_length=30, verbose_name='Фамилия')),
                ('display_name', models.IntegerField(choices=[(0, 'Почта'), (1, 'Логин'), (2, 'Имя и фамилия')], default=0, verbose_name='Имя пользователя на сайте')),
                ('photo', models.ImageField(upload_to='user', verbose_name='Аватар')),
                ('link_network', models.CharField(max_length=50, verbose_name='Ссылка на профиль в соц.сети')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('mail_tempkey', models.CharField(blank=True, max_length=30, verbose_name='Временный ключ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
